# Generated by Django 3.1.1 on 2020-09-14 06:17

import bullboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descr', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('avatar', models.ImageField(default=None, upload_to=bullboard.models.avatar_path)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=75)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_ad', models.ImageField(upload_to=bullboard.models.ads_path)),
                ('ad_categ', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bullboard.categories')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='users_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
