# Generated by Django 3.1.1 on 2020-09-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='title',
            new_name='title_ad',
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bullboard.categories'),
        ),
    ]
