# Generated by Django 3.1.1 on 2020-09-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullboard', '0002_auto_20200914_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='ad_categ',
            new_name='categ',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='title_ad',
            new_name='title',
        ),
    ]
