# Generated by Django 3.1.1 on 2020-09-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullboard', '0003_auto_20200915_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
